ALTER SESSION SET CURRENT_SCHEMA = IMS_ADMIN;
SET SERVEROUTPUT ON;

EXECUTE TOGGLE_SHIP_STATUS_UP(4010);

select * from LOGISTIC_ADMIN_ORDER_STATUS order by 2 desc;

EXECUTE TOGGLE_SHIP_STATUS_UP(4011);

EXECUTE TOGGLE_SHIP_STATUS_UP(4012);

select* from role_tab_privs;